name: Deploy to SFTP on push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to SFTP Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload via SFTP
        uses: appleboy/sftp-action@v0.0.4
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}  # Or use 'key' and 'passphrase' if using SSH key auth
          port: 2022
          source: "."                         # Consider using something more specific like `dist/**`
          target: "/"                         # Remote directory to upload to
          strip_components: 0
