name: Deploy to SFTP on main push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install tools, filter files, upload via SFTP, and clean up
        env:
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
          SFTP_PORT: 2022
          SFTP_USER: ${{ secrets.SFTP_USER }}
          SFTP_PASS: ${{ secrets.SFTP_PASS }}
        run: |
          echo "Installing required tools..."
          sudo apt-get update && sudo apt-get install -y lftp rsync git

          echo "Preparing filtered files (honoring .gitignore)..."
          mkdir filtered
          rsync -a --exclude-from='.gitignore' ./ filtered/

          echo "Uploading to SFTP root via lftp..."
          lftp -u "$SFTP_USER","$SFTP_PASS" sftp://$SFTP_HOST:$SFTP_PORT <<EOF
          mirror -R ./filtered /
          bye
          EOF

          echo "Cleaning up temporary files..."
          rm -rf filtered
